[package]
name = "conduwuit_direct_tls"
description = "Optional direct TLS listener for integration tests"
edition = "2024"
license = "Apache-2.0"
version = "0.5.10"

[lib]
path = "lib.rs"

[dependencies]
conduwuit_core = { path = "../core", version = "0.5.10" }
hyper = { version = "1.6.0", default-features = false, features = ["server", "http1", "http2"] }
log = { version = "0.4.27", default-features = false }
smol = "2.0.2"
