use std::{collections::BTreeMap, sync::Arc};

use crate::{Engine, Map};

pub(super) type Maps = BTreeMap<MapsKey, MapsVal>;
pub(super) type MapsKey = &'static str;
pub(super) type MapsVal = Arc<Map>;

const MAP_NAMES: &[&str] = &[
	"alias_roomid",
	"alias_userid",
	"aliasid_alias",
	"backupid_algorithm",
	"backupid_etag",
	"backupkeyid_backup",
	"bannedroomids",
	"delayid_finalizeddelayedevent",
	"delayid_scheduleddelayedevent",
	"deviceleftid_userid",
	"disabledroomids",
	"email_localpart",
	"eventid_metadata",
	"eventid_pdu",
	"eventid_pduid",
	"eventid_rejections",
	"eventid_shorteventid",
	"eventid_softfailed",
	"eventid_status",
	"fallbackkeyid_fallbackkey",
	"federation_outbound_to_device",
	"global",
	"id_appserviceregistrations",
	"keychangeid_userid",
	"keyid_key",
	"lazyloadedids",
	"localpart_email",
	"logintoken_expiresatuserid",
	"mediaid_file",
	"mediaid_user",
	"msc2836_children",
	"msc2836_reported_children",
	"onetimekeyid_onetimekeys",
	"openidtoken_expiresatuserid",
	"passwordresettoken_info",
	"presenceid_presence",
	"publicroomids",
	"pushkey_deviceid",
	"readreceiptid_readreceipt",
	"referencedevents",
	"registrationtoken_info",
	"rejectedeventids",
	"room_pducount_eventid",
	"room_pducount_eventid_backup",
	"roomid_depth_missingeventid",
	"roomid_invitedcount",
	"roomid_inviteviaservers",
	"roomid_joinedcount",
	"roomid_missingeventid_depth",
	"roomid_pduleaves",
	"roomid_roomversion",
	"roomid_roothandle",
	"roomid_shortroomid",
	"roomid_shortstatehash",
	"roomid_timestamp_pducount",
	"roomid_topologicalorder_pducount",
	"roomserverids",
	"roomsynctoken_shortstatehash",
	"roomuserdataid_accountdata",
	"roomuserid_forgotten",
	"roomuserid_invitecount",
	"roomuserid_joined",
	"roomuserid_knockedcount",
	"roomuserid_lastnotificationread",
	"roomuserid_lastprivatereadupdate",
	"roomuserid_leftcount",
	"roomuserid_privateread",
	"roomuserid_privatereadevent",
	"roomuserid_privatereadreceipt",
	"roomuserid_readreceipt",
	"roomuseroncejoinedids",
	"roomusertype_roomuserdataid",
	"senderkey_pusher",
	"server_signingkeys",
	"servercurrentevent_data",
	"servername_destination",
	"servername_educount",
	"servername_override",
	"servernameevent_data",
	"serverroomids",
	"shorteventid_authchain",
	"shorteventid_eventid",
	"shorteventid_roothandle",
	"shorteventid_shortauthevents",
	"shorteventid_shortprevevents",
	"shorteventid_shortstatehash",
	"shortstatehash_lthash",
	"shortstatehash_statediff",
	"shortstatekey_statekey",
	"state_hamt_node_mtimes",
	"state_hamt_nodes",
	"state_hamt_root_lattices",
	"statehash_shortstatehash",
	"statekey_shortstatekey",
	"threadid_userids",
	"todeviceid_events",
	"tofrom_relation",
	"token_userdeviceid",
	"tokenids",
	"url_previews",
	"userdeviceid_metadata",
	"userdeviceid_token",
	"userdevicesessionid_uiaainfo",
	"userdevicetxnid_response",
	"userfilterid_filter",
	"userid_avatarurl",
	"userid_blurhash",
	"userid_dehydrateddevice",
	"userid_devicelistversion",
	"userid_displayname",
	"userid_lastonetimekeyupdate",
	"userid_lastremotedeviceliststreamid",
	"userid_lock",
	"userid_logindisabled",
	"userid_masterkeyid",
	"userid_origin",
	"userid_password",
	"userid_presenceid",
	"userid_selfsigningkeyid",
	"userid_suspension",
	"userid_usersigningkeyid",
	"useridprofilekey_value",
	"userprofileupdate_value",
	"userroomdelayid",
	"userroomid_highlightcount",
	"userroomid_invitesender",
	"userroomid_invitestate",
	"userroomid_joined",
	"userroomid_knockedstate",
	"userroomid_leftstate",
	"userroomid_notificationcount",
	"userroomthread_subscription",
];

pub(super) fn open(db: &Arc<Engine>) -> Maps {
	MAP_NAMES
		.iter()
		.copied()
		.map(|name| (name, Map::open(db, name).expect("failed to open metadata map")))
		.collect()
}

pub(super) fn descriptors() -> &'static [&'static str] { MAP_NAMES }

pub fn column_family_names() -> &'static [&'static str] { MAP_NAMES }
