[package]
name = "conduwuit_core"
description.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lib]
path = "mod.rs"
crate-type = [
	"rlib",
#	"dylib",
]

[features]
conduwuit_mods = [
    "dep:libloading"
]
hardened_malloc = [
	"dep:hardened_malloc-rs"
]
mimalloc = [
	"dep:mimalloc",
]
mimalloc_conf = []
mimalloc_prof = []
mimalloc_stats = []
release_max_log_level = [
	"log/max_level_trace",
	"log/release_max_level_info",
]
zstd_compression = [
    # "reqwest/zstd",
]

[dependencies]
argon2.workspace = true
arrayvec.workspace = true
blocking.workspace = true
base64.workspace = true
bytes.workspace = true
bytesize.workspace = true
checked_ops.workspace = true
chrono.workspace = true
clap.workspace = true
conduwuit-macros.workspace = true
const-str.workspace = true
core_affinity.workspace = true
ctor.workspace = true
cyborgtime.workspace = true
either.workspace = true
futures.workspace = true
futures-io.workspace = true
http.workspace = true
hyper.workspace = true
libc.workspace = true
libloading.workspace = true
libloading.optional = true
log.workspace = true
num-traits.workspace = true
rand.workspace = true
# tied to passwordhash 0.5.0
rand_core = { version = "0.6.4", features = ["getrandom"] }
regex.workspace = true
rezzy.workspace = true
slipstream.workspace = true
sha2.workspace = true
serde.workspace = true
smallvec.workspace = true
smallstr.workspace = true
thiserror.workspace = true
mimalloc.optional = true
mimalloc.workspace = true
smol.workspace = true
tokio.workspace = true
toml.workspace = true
url.workspace = true
roaring.workspace = true
parking_lot.workspace = true
lock_api.workspace = true
dashmap.workspace = true
rustc-hash.workspace = true

[target.'cfg(unix)'.dependencies]
nix.workspace = true

[target.'cfg(all(not(target_env = "msvc"), target_os = "linux"))'.dependencies]
hardened_malloc-rs.workspace = true
hardened_malloc-rs.optional = true

[dev-dependencies]
blake3 = "1"
maplit.workspace = true

[lints]
workspace = true
